name: lasts
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.20.3
  - tensorflow>=2.3.0
  - tensorflow-probability=0.12.2
  - tslearn=0.5.1.0
  - jupyter=1.0.0
  - pandas=1.3.3
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - dill=0.3.4
  - imbalanced-learn=0.8.1 
  - requests=2.26.0
  - bitarray=2.3.0
  - tqdm=4.62.2
  - terminaltables=3.1.0
  - cython=0.29.24
  - shap=0.39.0
  - pyts=0.11.0
  - graphviz=2.48.0
  - stumpy=1.9.2
  - seaborn=0.11.2
  - python-graphviz=0.16
  - ruptures=1.1.4 
  - scikit-image=0.18.1
  - setuptools=52.0.0
  - pip=21.2.2
  - pip:
    - deap==1.3.1
    - liac-arff==2.5.0
    - scikit-multilearn==0.2.0
    - anchor-exp==0.0.2.0
    - sktime==0.7.0
